const technologies = [
  { value: "html", label: "HTML" },
  { value: "css", label: "CSS" },
  { value: "javascript", label: "JavaScript" },
  { value: "typescript", label: "TypeScript" },
  { value: "react", label: "React" },
  { value: "next", label: "Next.js" },
  { value: "vue", label: "Vue.js" },
  { value: "angular", label: "Angular" },
  { value: "svelte", label: "Svelte" },
  { value: "node", label: "Node.js" },
  { value: "express", label: "Express.js" },
  { value: "nest", label: "NestJS" },
  { value: "django", label: "Django" },
  { value: "flask", label: "Flask" },
  { value: "fastapi", label: "FastAPI" },
  { value: "laravel", label: "Laravel" },
  { value: "spring", label: "Spring" },
  { value: "php", label: "PHP" },
  { value: "python", label: "Python" },
  { value: "java", label: "Java" },
  { value: "kotlin", label: "Kotlin" },
  { value: "csharp", label: "C#" },
  { value: "dotnet", label: ".NET" },
  { value: "golang", label: "Go" },
  { value: "rust", label: "Rust" },
  { value: "ruby", label: "Ruby" },
  { value: "rails", label: "Ruby on Rails" },
  { value: "mysql", label: "MySQL" },
  { value: "postgresql", label: "PostgreSQL" },
  { value: "mongodb", label: "MongoDB" },
  { value: "redis", label: "Redis" },
  { value: "docker", label: "Docker" },
  { value: "kubernetes", label: "Kubernetes" },
  { value: "aws", label: "AWS" },
  { value: "azure", label: "Azure" },
  { value: "gcp", label: "Google Cloud Platform" },
  { value: "firebase", label: "Firebase" },
  { value: "graphql", label: "GraphQL" },
  { value: "restapi", label: "REST API" },
  { value: "ci_cd", label: "CI/CD" },
  { value: "git", label: "Git" },
  { value: "webpack", label: "Webpack" },
  { value: "vite", label: "Vite" },
  { value: "babel", label: "Babel" },
  { value: "eslint", label: "ESLint" },
  { value: "prettier", label: "Prettier" },
  { value: "tailwind", label: "Tailwind CSS" },
  { value: "sass", label: "Sass" },
  { value: "materialui", label: "Material UI" },
];
export { technologies };
